### ISSUE TITLE
Installing “revealjs-preview@0.3.1” failed.Hide output…

### ISSUE THREAD

**Issue by Bjorn-c** [keqh/revealjs-preview#12]
Installing “revealjs-preview@0.3.1” failed.Hide output…

```
Installing “revealjs-preview@0.3.1” failed.Hide output…

npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\cwn8400\\AppData\\Local\\atom\\app-1.13.0-beta3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\cwn8400\\AppData\\Local\\atom\\app-1.13.0-beta3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\cwn8400\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\cwn8400\\.atom\\.apmrc" "install" "C:\\Users\\cwn8400\\AppData\\Local\\Temp\\d-1161024-14152-1rh6neu\\package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! file C:\Users\cwn8400\.atom\.apm\inherits\2.0.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\cwn8400\.atom\.apm\inherits\2.0.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
```

**Comment by franlbc97** [comment]
1. can't install this package by the easy way in atom 
2. download this as a .zip, 
3. unzip in .atom\packages\
4. open atom and this happens

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
### Stack Trace

Failed to load the revealjs-preview package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/FRANCISCO-SOLANOLOPE/.atom/packages/revealjs-preview-master/lib/revealjs-preview.coffee:1:6)
    at Object.<anonymous> (file:///C:/Users/FRANCISCO-SOLANOLOPE/.atom/packages/revealjs-preview-master/lib/revealjs-preview.coffee:1:1)
    at Module._compile (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:766:27)
    at C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:121:28
    at Package.module.exports.Package.measure (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:94:15)
    at Package.module.exports.Package.load (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:108:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:468:14)
    at C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:412:19
    at Config.module.exports.Config.transact (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:407:19)
    at C:\Users\FRANCISCO-SOLANOLOPE\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:811:28
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
